### ISSUE TITLE
Very old StatsBase version bound in AdaptiveRejectionSampling v0.2.0

### ISSUE THREAD

**Issue by oschulz** [mauriciogtec/AdaptiveRejectionSampling.jl#23]
The new AdaptiveRejectionSampling v0.2.0 only supports StatsBase v0.24 (see 
https://github.com/JuliaRegistries/General/blob/master/A/AdaptiveRejectionSampling/Compat.toml) which is very old. Is that intentional?

**Comment by mauriciogtec** [comment]
Version is now 0.2.1

**Comment by oschulz** [comment]
Thanks @mauriciogtec !
