### ISSUE TITLE
Allow setting the RNG

### ISSUE THREAD

**Issue by oschulz** [mauriciogtec/AdaptiveRejectionSampling.jl#4]
Having

    run_sampler!(rng::AbstractRNG, s::RejectionSampler, n::Int)

would be useful.

@mauriciogtec , if this package is still active, would you accept a PR for this?

**Comment by mauriciogtec** [comment]
Yes absolutely! Thanks.

**Comment by oschulz** [comment]
Thanks, will get on it!

We'll probably need this, first: #5 :-)

**Comment by oschulz** [comment]
Ready: #6 :-)

**Comment by mauriciogtec** [comment]
Thanks!

**Comment by oschulz** [comment]
Could you do a `@JuliaRegistrator register`? We'd like to use your nice package in BAT.jl. :-)
