### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by oschulz** [mauriciogtec/AdaptiveRejectionSampling.jl#7]
@mauriciogtec , it would be great if you could tag a new release - a `@JuliaRegistrator register` comment on 54c3933 should be enough (since the version was already increased in #6).

I don't want to seem pushy - it's just that I'd like to use your package in [BAT.jl](https://github.com/bat/BAT.jl), but I need the ability to set the RNG.

**Comment by mauriciogtec** [comment]
I'm glad this is going to be useful! I believed I have tagged it.

**Comment by oschulz** [comment]
Yep, it's in General now - thanks!!
